services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: who-eats-who-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        NEXT_PUBLIC_FREESOUND_KEY: ${NEXT_PUBLIC_FREESOUND_KEY}
    container_name: who-eats-who-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped
